#!/bin/bash
echo "Synchronizing nodes.."
unison -batch -prefer newer -times=true ../MPICluster ssh://acl@acl07/MPICluster
unison -batch -prefer newer -times=true ../MPICluster ssh://acl@acl08/MPICluster
echo "---------------------------------------------------"
echo "Compiling.."
mpicc -o $1'_mpi' $1.c
echo "Compilation done."
echo "---------------------------------------------------"
echo "Synchronizing nodes.."
unison -batch -prefer newer -times=true ../MPICluster ssh://acl@acl07/MPICluster
unison -batch -prefer newer -times=true ../MPICluster ssh://acl@acl08/MPICluster
echo "---------------------------------------------------"
echo "Running MPI job.."
mpirun --hostfile host_file $1'_mpi'
